topic:
  name: javatechie-avro

server:
  port: 8181

spring:
  kafka:
    bootstrap-servers: "192.168.0.106:9092"
    producer:
      keySerializer: "org.apache.kafka.common.serialization.StringSerializer"
      # Bellow is the Avro Serializer not the normal one
      valueSerializer: "io.confluent.kafka.serializers.KafkaAvroSerializer"
      properties:
        # Schema registry properties are below
        schema:
          registry:
            url: "http://192.168.0.106:8081"
    consumer:
      group-id: "javatechie-new"
      keyDeserializer: "org.apache.kafka.common.serialization.StringDeserializer"
      # Bellow is the Avro Deserializer not the normal one
      valueDeserializer: "io.confluent.kafka.serializers.KafkaAvroDeserializer"
      autoOffsetReset: "earliest"
      properties:
        # Schema registry properties are below
        schema:
          registry:
            url: "http://192.168.0.106:8081"
        specific:
          avro:
            reader: "true"
